config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'

  resources :hotels do
    collection do
      get 'my_hotels', to: 'hotels#my_hotels'
      get 'search', to: 'hotels#search'  # ここを追加
    end
    resources :reservations, only: [:new, :create, :show, :index, :edit, :update, :destroy]
  end

  resources :reservations, only: [:index]

  resource :account_settings, only: [] do
    collection do
      get 'show_account', to: 'account_settings#show_account'
      get 'edit_account', to: 'account_settings#edit_account'
      patch 'update_account', to: 'account_settings#update_account'
      get 'show_profile', to: 'account_settings#show_profile'
      get 'edit_profile', to: 'account_settings#edit_profile'
      patch 'update_profile', to: 'account_settings#update_profile'
    end
  end

  get 'home/index'

  # 既存のルーティング
  get 'hotels/index'
  get 'hotels/new'
  get 'hotels/create'
  get 'hotels/edit'
  get 'hotels/update'
  get 'hotels/show'
  get 'hotels/destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :reservations, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :address, presence: true

  # スコープを追加
  scope :search_by_area, -> (area) { where('address LIKE ?', "%#{area}%") }
  scope :search_by_keyword, -> (keyword) { where('name LIKE ? OR description LIKE ?', "%#{keyword}%", "%#{keyword}%") }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :hotel
  belongs_to :user

  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :number_of_people, numericality: { greater_than_or_equal_to: 1, message: :greater_than_or_equal_to }

  validate :check_in_cannot_be_in_the_past
  validate :check_out_must_be_after_check_in

  private

  def check_in_cannot_be_in_the_past
    if check_in.present? && check_in < Date.today
      errors.add(:check_in, :check_in_cannot_be_in_the_past)
    end
  end

  def check_out_must_be_after_check_in
    if check_in.present? && check_out.present? && check_out <= check_in
      errors.add(:check_out, :check_out_must_be_after_check_in)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
       has_many :hotels
       devise :database_authenticatable, :registerable,
              :recoverable, :rememberable, :validatable
       mount_uploader :profile_image, ProfileImageUploader
       has_many :reservations
     
       validates :name, presence: true
     end
     

app/controllers/account_settings_controller.rb
class AccountSettingsController < ApplicationController
  before_action :authenticate_user!

  def show_account
    @user = current_user
  end

  def edit_account
    @user = current_user
  end

  def update_account
    @user = current_user
    if @user.update_with_password(user_params)
      bypass_sign_in(@user)
      redirect_to show_account_settings_path, notice: 'アカウント情報を更新しました。'
    else
      render :edit_account
    end
  end

  def show_profile
    @user = current_user
  end

  def edit_profile
    @user = current_user
  end

  def update_profile
    @user = current_user
    if @user.update(profile_params)
      redirect_to show_profile_account_settings_path, notice: 'プロフィールを更新しました。'
    else
      render :edit_profile
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :current_password)
  end

  def profile_params
    params.require(:user).permit(:name, :profile_image, :bio)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]

  def index
    @hotels = if params[:area].present? && params[:keyword].present?
                Hotel.search_by_area(params[:area]).search_by_keyword(params[:keyword])
              elsif params[:area].present?
                Hotel.search_by_area(params[:area])
              elsif params[:keyword].present?
                Hotel.search_by_keyword(params[:keyword])
              else
                Hotel.all
              end
  end

  def my_hotels
    @hotels = current_user.hotels
  end

  def show
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = current_user.hotels.new(hotel_params)
    if @hotel.save
      redirect_to my_hotels_hotels_path, notice: 'ホテルが作成されました。'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @hotel.update(hotel_params)
      redirect_to my_hotels_hotels_path, notice: 'ホテルが更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @hotel.destroy
    redirect_to my_hotels_hotels_path, notice: 'ホテルが削除されました。'
  end

  def search
    @hotels = if params[:area].present?
                Hotel.search_by_area(params[:area])
              else
                Hotel.all
              end
    render :index
  end

  private

  def set_hotel
    @hotel = Hotel.find(params[:id])
  end

  def hotel_params
    params.require(:hotel).permit(:name, :description, :price, :address, :image)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_hotel, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  def new
    @reservation = Reservation.new(
      check_in: params[:check_in],
      check_out: params[:check_out],
      number_of_people: params[:number_of_people]
    )
  end

  def create
    @reservation = @hotel.reservations.new(reservation_params)
    @reservation.user = current_user
    if @reservation.save
      redirect_to hotel_reservations_path(@hotel), notice: '予約が完了しました。'
    else
      render :new
    end
  end

  def show
  end

  def index
    @reservations = current_user.reservations.includes(:hotel)
  end

  def edit
  end

  def update
    if @reservation.update(reservation_params)
      redirect_to hotel_reservations_path(@hotel), notice: '施設の予約情報を更新しました。'
    else
      flash.now[:alert] = '予約情報の更新に失敗しました。'
      render :edit
    end
  end

  def destroy
    @reservation.destroy
    redirect_to hotel_reservations_path(@hotel), notice: '施設の予約情報を削除しました。'
  end

  private

  def set_hotel
    @hotel = Hotel.find(params[:hotel_id])
  end

  def set_reservation
    @reservation = Reservation.find(params[:id])
  end

  def reservation_params
    params.require(:reservation).permit(:check_in, :check_out, :number_of_people)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def custom_form_with(**args, &block)
      form_with(**args.merge(builder: CustomFormBuilder), &block)
    end
  end
  

app/helpers/custom_form_builder.rb
class CustomFormBuilder < ActionView::Helpers::FormBuilder
    include ActionView::Helpers::TagHelper
  
    def text_field(method, options = {})
      field_with_errors(method) do
        super(method, options.merge(class: "form-control"))
      end
    end
  
    def date_field(method, options = {})
      field_with_errors(method) do
        super(method, options.merge(class: "form-control"))
      end
    end
  
    def number_field(method, options = {})
      field_with_errors(method) do
        super(method, options.merge(class: "form-control"))
      end
    end
  
    private
  
    def field_with_errors(method)
      error_messages = object.errors.full_messages_for(method).map do |msg|
        @template.content_tag(:div, msg, class: 'text-danger error-messages')
      end.join.html_safe
  
      @template.content_tag(:div, class: 'form-group custom-form-group') do
        yield + error_messages
      end
    end
  end
  

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/views/account_settings/_settings_navigation.html.erb
<div class="settings-navigation">
  <h2>設定</h2>
  <ul>
    <li class="<%= 'active' if current_page?(edit_account_account_settings_path) || current_page?(show_account_account_settings_path) %>">
      <%= link_to 'アカウント', show_account_account_settings_path %>
    </li>
    <li class="<%= 'active' if current_page?(edit_profile_account_settings_path) || current_page?(show_profile_account_settings_path) %>">
      <%= link_to 'プロフィール', show_profile_account_settings_path %>
    </li>
  </ul>
</div>

app/views/account_settings/edit_account.html.erb
<main class="account-settings-main">
  <%= render 'account_settings/settings_navigation' %>
  <div class="account-edit">
    <h3>アカウント</h3>
    <%= form_with model: @user, url: update_account_account_settings_path do |f| %>
      <div class="field">
        <%= f.label :email, 'メールアドレス' %>
        <%= f.email_field :email %>
      </div>
      <div class="field">
        <%= f.label :password, '変更後パスワード' %>
        <%= f.password_field :password %>
      </div>
      <div class="field">
        <%= f.label :password_confirmation, '確認用パスワード' %>
        <%= f.password_field :password_confirmation %>
      </div>
      <div class="field">
        <%= f.label :current_password, '現在のパスワード' %>
        <%= f.password_field :current_password %>
      </div>
      <div class="actions">
        <%= f.submit '保存', class: 'btn btn-primary' %>
        <%= link_to 'キャンセル', show_account_account_settings_path, class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</main>

app/views/account_settings/edit_profile.html.erb
<main class="account-settings-main">
  <%= render 'account_settings/settings_navigation' %>
  <div class="profile-edit">
    <h3>プロフィール</h3>
    <%= form_for(@user, url: update_profile_account_settings_path, html: { method: :patch }) do |f| %>
      <div class="form-group">
        <%= f.label :profile_image, 'アイコン画像' %>
        <% if @user.profile_image.present? %>
          <%= image_tag @user.profile_image.url, class: 'profile-image' %>
        <% else %>
          <%= image_tag 'https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png', class: 'profile-image' %>
        <% end %>
        <%= f.file_field :profile_image %>
      </div>
      <div class="form-group">
        <%= f.label :name, '名前' %>
        <%= f.text_field :name %>
      </div>
      <div class="form-group">
        <%= f.label :bio, '自己紹介' %>
        <%= f.text_area :bio %>
      </div>
      <div class="form-actions">
        <%= f.submit '保存', class: 'btn btn-primary' %>
        <%= link_to 'キャンセル', show_profile_account_settings_path, class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</main>

app/views/account_settings/show_account.html.erb
<main class="account-settings-main">
  <%= render 'account_settings/settings_navigation' %>
  <div class="account-show">
    <h3>アカウント</h3>
    <%= link_to '編集', edit_account_account_settings_path, class: 'edit-link' %>
    <p><strong>メールアドレス:</strong> <%= @user.email %></p>
    <p><strong>パスワード:</strong> *********</p>
  </div>
</main>

app/views/account_settings/show_profile.html.erb
<main class="account-settings-main">
  <%= render 'account_settings/settings_navigation' %>
  <div class="profile-show">
    <h3>プロフィール</h3>
    <%= link_to '編集', edit_profile_account_settings_path, class: 'edit-link' %>
    <p><strong>アイコン画像:</strong> 
      <% if @user.profile_image.present? %>
        <%= image_tag @user.profile_image.url, class: 'profile-image' %>
      <% else %>
        <%= image_tag 'https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png', class: 'profile-image' %>
      <% end %>
    </p>
    <p><strong>名前:</strong> <%= @user.name %></p>
    <p><strong>自己紹介:</strong> <%= @user.bio %></p>
  </div>
</main>

app/views/home/index.html.erb
<div class="FirstView">
  <section class="container">
    <h2 class="FirstView__title">
      Potepan Shareで<br>
      まだ体験したことのない<br>
      旅をしよう
    </h2>

    <div class="FirstViewSearch">
      <%= form_with url: search_hotels_path, method: :get, local: true do %>
        <%= text_field_tag :area, params[:area], class: 'form-control FirstViewSearch__input', placeholder: 'エリア名を入力' %>
        <%= submit_tag '検索', class: 'btn FirstViewSearch__button' %>
      <% end %>
    </div>
  </section>
</div>

<div class="container">
  <section class="RecommendAreaSection">
    <h2 class="RecommendAreaSection__title">
      おすすめのエリア
    </h2>

    <div class="RecommendAreas">
      <a class="RecommendArea" href="<%= search_hotels_path(area: '東京') %>">
        <img src="https://rails-02-sample.herokuapp.com/assets/home/recommend-area/tokyo.jpg" alt="東京">
        <span class="RecommendArea__name RecommendArea__name--ja">東京</span>
        <span class="RecommendArea__name RecommendArea__name--en">Tokyo</span>
      </a>
      <a class="RecommendArea" href="<%= search_hotels_path(area: '大阪') %>">
        <img src="https://rails-02-sample.herokuapp.com/assets/home/recommend-area/osaka.jpg" alt="大阪">
        <span class="RecommendArea__name RecommendArea__name--ja">大阪</span>
        <span class="RecommendArea__name RecommendArea__name--en">Osaka</span>
      </a>
      <a class="RecommendArea" href="<%= search_hotels_path(area: '京都') %>">
        <img src="https://rails-02-sample.herokuapp.com/assets/home/recommend-area/kyoto.jpg" alt="京都">
        <span class="RecommendArea__name RecommendArea__name--ja">京都</span>
        <span class="RecommendArea__name RecommendArea__name--en">Kyoto</span>
      </a>
      <a class="RecommendArea" href="<%= search_hotels_path(area: '札幌') %>">
        <img src="https://rails-02-sample.herokuapp.com/assets/home/recommend-area/sapporo.jpg" alt="札幌">
        <span class="RecommendArea__name RecommendArea__name--ja">札幌</span>
        <span class="RecommendArea__name RecommendArea__name--en">Sapporo</span>
      </a>
    </div>
  </section>
</div>

app/views/hotels/create.html.erb
<h1>Hotels#create</h1>
<p>Find me in app/views/hotels/create.html.erb</p>

app/views/hotels/edit.html.erb
<main class="new-hotel-form">
  <div class="account-settings">
    <div class="settings-content">
      <h2>施設情報の編集</h2>
      <%= form_with(model: @hotel, local: true, builder: ActionView::Helpers::FormBuilder, class: "form-horizontal") do |form| %>
        
        <div class="form-group">
          <%= form.label :name, "施設名", class: "control-label" %>
          <div class="form-control-wrapper">
            <%= form.text_field :name, class: "form-control", placeholder: "ルーム名を入力" %>
            <% if @hotel.errors[:name].present? %>
              <div class="text-danger">
                <%= @hotel.errors[:name].first %>
              </div>
            <% end %>
          </div>
        </div>
        
        <div class="form-group">
          <%= form.label :description, "施設詳細", class: "control-label" %>
          <div class="form-control-wrapper">
            <%= form.text_area :description, class: "form-control", placeholder: "施設詳細を入力" %>
            <% if @hotel.errors[:description].present? %>
              <div class="text-danger">
                <%= @hotel.errors[:description].first %>
              </div>
            <% end %>
          </div>
        </div>
        
        <div class="form-group">
          <%= form.label :price, "料金", class: "control-label" %>
          <div class="form-control-wrapper">
            <%= form.number_field :price, class: "form-control", placeholder: "一日あたりの料金を入力" %>
            <% if @hotel.errors[:price].present? %>
              <div class="text-danger">
                <%= @hotel.errors[:price].first %>
              </div>
            <% end %>
          </div>
        </div>
        
        <div class="form-group">
          <%= form.label :address, "住所", class: "control-label" %>
          <div class="form-control-wrapper">
            <%= form.text_field :address, class: "form-control", placeholder: "住所を入力" %>
            <% if @hotel.errors[:address].present? %>
              <div class="text-danger">
                <%= @hotel.errors[:address].first %>
              </div>
            <% end %>
          </div>
        </div>
        
        <div class="form-group">
          <%= form.label :image, "施設画像", class: "control-label" %>
          <div class="form-control-wrapper">
            <%= form.file_field :image, class: "form-control" %>
            <% if @hotel.errors[:image].present? %>
              <div class="text-danger">
                <%= @hotel.errors[:image].first %>
              </div>
            <% end %>
          </div>
        </div>
        
        <div class="form-actions">
          <%= form.submit "保存", class: "btn btn-primary" %>
          <%= link_to "キャンセル", hotels_path, class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/hotels/index.html.erb
<%= render 'shared/search_form' %>
<div class="hotels-index">
  <h2><%= @hotels.count %> 件が見つかりました。</h2>
  <div class="card-deck">
    <% @hotels.each do |hotel| %>
      <div class="card">
        <% if hotel.image.present? %>
          <%= image_tag hotel.image.url, class: "card-img-top" %>
        <% else %>
          <%= image_tag 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png', class: "card-img-top" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= hotel.name %></h5>
          <p class="card-address"><%= hotel.address %></p>
          <p class="card-description"><%= hotel.description %></p>
          <div class="card-price-and-button">
            <p class="card-price"><%= number_to_currency(hotel.price, unit: "¥", precision: 0) %>~</p>
            <%= link_to '詳細はこちら', hotel_path(hotel), class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/hotels/my_hotels.html.erb
<h1>登録済み一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>料金</th>
      <th>作成日</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= image_tag hotel.image.present? ? hotel.image.url : 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png', size: '100x100' %></td>
        <td><%= link_to hotel.name, hotel_path(hotel) %></td>
        <td><%= hotel.description %></td>
        <td><%= number_to_currency(hotel.price, unit: "¥", precision: 0) %></td>
        <td><%= hotel.created_at.strftime('%Y/%m/%d') %></td>
        <td>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              ⋮
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to '編集', edit_hotel_path(hotel), class: 'dropdown-item' %>
              <a href="#" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#deleteModal" data-hotel-name="<%= hotel.name %>" data-delete-url="<%= hotel_path(hotel) %>">削除</a>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/hotels/show.html.erb
<%= render 'shared/search_form' %>
<div class="hotel-show">
  <div class="hotel-show__image">
    <%= image_tag @hotel.image.present? ? @hotel.image.url : 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png' %>
  </div>
  <div class="hotel-show__details">
    <h2><%= @hotel.name %></h2>
    <p><%= @hotel.address %></p>
    <div class="hotel-show__price">
      <p><%= "¥#{number_to_currency(@hotel.price, unit:"",precision: 0)}~" %></p>
    </div>
    <p><%= @hotel.description %></p>
    <%= form_with(url: new_hotel_reservation_path(@hotel), method: :get, local: true, id: "reservation-form") do %>
      <div class="hotel-show__form-group-row">
        <div class="hotel-show__form-group">
          <label for="check_in">チェックイン</label>
          <%= date_field_tag :check_in, nil, class: 'form-control' %>
          <small class="text-danger"></small>
        </div>
        <div class="hotel-show__form-group">
          <label for="check_out">チェックアウト</label>
          <%= date_field_tag :check_out, nil, class: 'form-control' %>
          <small class="text-danger"></small>
        </div>
        <div class="hotel-show__form-group">
          <label for="number_of_people">人数</label>
          <%= number_field_tag :number_of_people, nil, class: 'form-control' %>
          <small class="text-danger"></small>
        </div>
      </div>
      <div class="hotel-show__form-actions">
        <%= submit_tag '予約する', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Potepan Share</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- CSSの読み込み -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- JavaScriptの読み込み -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <nav class="nav-wrapper">
      <div class="container">
        <a href="/" class="brand-logo">
          <img src="https://rails-02-sample.herokuapp.com/assets/common/logo.png" alt="Potepan Share">
        </a>
        <ul id="nav-mobile" class="right">
          <% if user_signed_in? %>
            <li>
              <a href="#" class="account-menu-toggle">
                <% if current_user.profile_image.present? %>
                  <img src="<%= current_user.profile_image.url %>" alt="Profile Image" class="profile-icon">
                <% else %>
                  <img src="https://rails-02-sample.herokuapp.com/assets/common/default-avatar-7a6cbfd7993e89f24bfc888f4a035a83c6f1428b8bdc47eed9095f2799a40153.png" alt="Default Avatar" class="profile-icon">
                <% end %>
                <%= current_user.name %>
              </a>
              <ul class="account-menu">
                <li><%= link_to '施設の新規登録', new_hotel_path %></li>
                <li class="separator"></li>
                <li><%= link_to '予約済み一覧', hotel_reservations_path(current_user) %></li>
                <li><%= link_to '登録済み一覧', my_hotels_hotels_path %></li>
                <li><%= link_to 'アカウント設定', show_account_account_settings_path %></li>
                <li class="separator"></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'ログイン', new_user_session_path %></li>
            <li><%= link_to '新規登録', new_user_registration_path, class: 'register-button' %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>
  <main>
    <%= yield %>
  </main>
  <footer>
    <div class="footer-content">
      <a href="/" class="footer-logo">
        <img src="https://rails-02-sample.herokuapp.com/assets/common/logo.png" alt="Potepan Share">
      </a>
      <p>&copy; Potepan Share 2024 All rights reserved</p>
    </div>
  </footer>

  <!-- 削除確認モーダル -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">削除の確認</h5>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p id="deleteModalBody"></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
          <button type="button" class="btn btn-danger" id="confirmDeleteButton">削除</button>
        </div>
      </div>
    </div>
  </div>

  <script>
    document.addEventListener('turbolinks:load', () => {
      // モーダルの初期化などのコードをここに追加
      $('#deleteModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget); // ボタンがモーダルをトリガーした
        var recipient = button.data('whatever'); // ボタンから情報を抽出

        // モーダルのボディに情報を更新
        var modal = $(this);
        modal.find('.modal-body').text('Are you sure you want to delete ' + recipient + '?');
      });
    });
  </script>
</body>
</html>

app/views/reservations/index.html.erb
<h1>予約済み一覧</h1>

<table class="table">
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>合計料金</th>
      <th>チェックイン</th>
      <th>チェックアウト</th>
      <th>予約確定日時</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= image_tag reservation.hotel.image.present? ? reservation.hotel.image.url : 'https://rails-02-sample.herokuapp.com/assets/room/default-image-4e0ac6b8d01335b5b22fe6586af13644ae51dddb6aeabf35b9174e80f13cd09d.png', size: '100x100' %></td>
        <td><%= link_to reservation.hotel.name, hotel_path(reservation.hotel) %></td>
        <td><%= reservation.hotel.description %></td>
        <td>¥<%= number_to_currency(reservation.hotel.price * (reservation.check_out - reservation.check_in).to_i, unit: "", precision: 0) %></td>
        <td><%= reservation.check_in.strftime('%Y/%m/%d') %></td>
        <td><%= reservation.check_out.strftime('%Y/%m/%d') %></td>
        <td><%= reservation.created_at.strftime('%Y/%m/%d %H:%M') %></td>
        <td>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              ⋮
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to '再予約', edit_hotel_reservation_path(reservation.hotel, reservation), class: 'dropdown-item' %>
              <a href="#" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#deleteModal" data-hotel-name="<%= reservation.hotel.name %>" data-check-in="<%= reservation.check_in %>" data-check-out="<%= reservation.check_out %>" data-number-of-people="<%= reservation.number_of_people %>" data-delete-url="<%= hotel_reservation_path(reservation.hotel, reservation) %>">予約を削除</a>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>